"""Add VideoCall model for call history tracking

Revision ID: 96fd46d6caaf
Revises: 807dc6f77f37
Create Date: 2025-10-06 08:18:38.849314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96fd46d6caaf'
down_revision = '807dc6f77f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('initiated_at', sa.DateTime(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('connection_quality', sa.String(length=20), nullable=True),
    sa.Column('audio_quality', sa.String(length=20), nullable=True),
    sa.Column('video_quality', sa.String(length=20), nullable=True),
    sa.Column('ended_by', sa.String(length=20), nullable=True),
    sa.Column('end_reason', sa.String(length=100), nullable=True),
    sa.Column('provider_notes', sa.Text(), nullable=True),
    sa.Column('patient_feedback', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_calls', schema=None) as batch_op:
        batch_op.create_index('idx_call_patient_date', ['patient_id', 'initiated_at'], unique=False)
        batch_op.create_index('idx_call_provider_date', ['provider_id', 'initiated_at'], unique=False)
        batch_op.create_index('idx_call_status_date', ['status', 'initiated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_calls_call_id'), ['call_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_video_calls_initiated_at'), ['initiated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_calls_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_calls_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_calls_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_calls_status'))
        batch_op.drop_index(batch_op.f('ix_video_calls_provider_id'))
        batch_op.drop_index(batch_op.f('ix_video_calls_patient_id'))
        batch_op.drop_index(batch_op.f('ix_video_calls_initiated_at'))
        batch_op.drop_index(batch_op.f('ix_video_calls_call_id'))
        batch_op.drop_index('idx_call_status_date')
        batch_op.drop_index('idx_call_provider_date')
        batch_op.drop_index('idx_call_patient_date')

    op.drop_table('video_calls')
    # ### end Alembic commands ###
